// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package mkpasswd

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	Plaintext *string `mapstructure:"plaintext" required:"true" cty:"plaintext" hcl:"plaintext"`
	Algorithm *string `mapstructure:"algorithm" required:"false" cty:"algorithm" hcl:"algorithm"`
	Salt      *string `mapstructure:"salt" required:"false" cty:"salt" hcl:"salt"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"plaintext": &hcldec.AttrSpec{Name: "plaintext", Type: cty.String, Required: false},
		"algorithm": &hcldec.AttrSpec{Name: "algorithm", Type: cty.String, Required: false},
		"salt":      &hcldec.AttrSpec{Name: "salt", Type: cty.String, Required: false},
	}
	return s
}

// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatDatasourceOutput struct {
	Result *string `mapstructure:"result" cty:"result" hcl:"result"`
}

// FlatMapstructure returns a new FlatDatasourceOutput.
// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*DatasourceOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatDatasourceOutput)
}

// HCL2Spec returns the hcl spec of a DatasourceOutput.
// This spec is used by HCL to read the fields of DatasourceOutput.
// The decoded values from this spec will then be applied to a FlatDatasourceOutput.
func (*FlatDatasourceOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"result": &hcldec.AttrSpec{Name: "result", Type: cty.String, Required: false},
	}
	return s
}
